c_stdlib:                  # [win]
- m2w64-sysroot            # [win]
c_stdlib_version:
- '12.3'                   # [osx]
- '12'                     # [win]
c_compiler:                # [win]
- gcc                      # [win]
c_compiler_version:        # [win]
- 14                       # [win]
cxx_compiler:              # [win]
- gxx                      # [win]
cxx_compiler_version:      # [win]
- 14                       # [win]
